### ISSUE TITLE
Use this to predict next char(s) based on a given prefix

### ISSUE THREAD

**Issue by mmahmad** [lakiw/py_omen#1]
Hi,

I would like to train a Markov model on a password dataset. Using the trained model, how can I modify the code to accept chars and predict next possible chars?

**Comment by lakiw** [comment]
Quick aside, I’m traveling back from PasswordsCon today so it’s hard for me to look at the code right now and replies may be spotty until tomorrow.

password_scorer.py would probably be the easiest part to modify to accomplish your goal. It currently “scores” passwords based on an existing rule set which is useful for research into better password strength metrics. Therefore, it already loads up an OMEN (Ordered Markov ENumerator) and applies it to an input password. It should hopefully be somewhat straightforward for it to instead recommend the “next” character instead. 

The complications I can foresee:
1) You’d probably want to strip out all the PCFG parsing and other scoring it does
2) Developing a better UI for your needs
3) OMEN while powerful, does sacrifice precision in its model for speed. There may be a better Markov algorithm for your use case since speed doesn’t seem as import.
4) related to #3, OMEN may suggest multiple options vs just one so picking which one you want may be tricky
5) Also related to #3, OMEN may not have a suggestion if it has never seen a given prefix before. So that’s an additional edge case which would need to be supported.

I’d be interested in hearing more about your use case so I can better tailor suggestions, and or code up a quick PoC.

**Comment by m33x** [comment]
This problem is very much related to [Natural Language Encoders](https://www.mobsec.ruhr-uni-bochum.de/forschung/veroeffentlichungen/cracking-resistant-password-vaults/).
Thus, it is rather straight forward to implement with [NEMO](https://github.com/RUB-SysSec/NEMO).

Here is the code, which is only a small modification of the file [meter.py](https://github.com/RUB-SysSec/NEMO/blob/master/meter.py) which is shipped with NEMO.
https://gist.github.com/m33x/9632d4c47483e5a6768865a485e71f40#file-predict-py-L95

This is what the output will look like:
`Given 'passwor' the top 5 most likely predictions are:`
`('password', 5.217937750136535e-07)`
`('passwork', 5.0743563645302264e-09)`
`('passwort', 1.311252190776853e-09)`
`('passworm', 2.1270776175931523e-10)`
`('passwore', 1.196025357549521e-10)`

This solution makes use of EPs (end probabilities) that you might not like to use, but this is up to you. In the past, we observed that including the EPs in the calculation can decrease guessing performance, but sometimes it does not change anything. So this is really up to you, whether you like to use them.

The approach I took can be considered brute-forcing. I use the pw_prefix and then calculate the probabilities for all possible passwords that are 1 char longer and can be built with the trained password dataset. Then I sort the result by probability. Done.

**Comment by lakiw** [comment]
Thank you very much @m33x!!! @mmahmad I'd recommend using the above option for your approach since it's probably much better suited for your needs than what is available in the PCFG repo. If there are additions you need though please post a follow-up comment talking in more detail about your use-case and I'll see what I can do to help. I'll keep this issue open for another week or so, and if I don't hear back from you I'll close it.

**Comment by mmahmad** [comment]
@m33x Excellent, this is exactly what I was looking for! My use-case is trying to integrate this on the client-side in a text-prediction kind of way (user types prefix of pwd, model predicts next).

I've created models for lengths 2-12. Since it takes quite some time to load the model, do you have any suggestions on how we speed up the prediction? I was thinking that maybe I could keep all models in RAM (on a server) and query for the predictions, but maybe there's a better way.

Appreciate your help!

@lakiw Since my follow-up is kind of off-topic, please let me know if you want us to take this conversation elsewhere.

**Comment by m33x** [comment]
## Warning ⚠️ this code is intended for research only and definitely not for production!

Yes, this is rather straightforward, I did so in the past, but for research purposes this hack is only complicating things. The idea:

- Do not store any possible ngram, but only the ones present in the training corpus. This way, you do not lose information, but you will simply no longer store ngrams with a count of 0 or 1 (smoothing). Example:

- aaa = 0
- aab = 0
- aac = 0
- ...
- pas = 736
- ...
- wor = 381

only store:
- pas = 736
- wor = 381

later if you need to know the count/prob of “aac” but this n-gram is not in the data structure, simply return a low default prob like 0.0000000001, done ✅

Optimizations (sorted by required time to implement):
- Use pypy instead of python
- Do not use n-gram size = 4 but for example n-gram size = 2 or 3.
- Limit the alphabet get rid of rare characters, like special characters
- Search for a better solution for your problem, text prediction (as it is available e.g. on mobile phone keyboards) is not implemented like this. I guess they are using a word instead of a ngram model there. There are libraries for that.
- Rewrite ngram creator to only store ngrams observed in the training corpus.
- Rewrite it in C

Remember training is a onetime task. Loading the trained ngrams from disk is a onetime task, too. Then you can keep it in memory and query the model using some sort of inter process communication like sockets (JavaScript Ajax Requests).

**Comment by mmahmad** [comment]
@m33x Thanks! I found the other implementation used by Melicher et al. which seems to work much faster for my use-case after some modifications. I don't think I'll be able to speed that up further and it's a good baseline for my research.
