### ISSUE TITLE
hello, i just wonder how the EP(end prob) is used in this model. For the createNG generate EP, but the enumNG totally not use this grammar and in the paper it is not mentioned either.

### ISSUE THREAD

**Issue by llCurious** [lakiw/py_omen#2]

**Comment by lakiw** [comment]
Excellent question! The short answer is it is not used in the model currently since its inclusion noticeably makes it worse at cracking passwords. This finding was verified by both the original OMEN developers as well as myself. I didn't take the code out though since it might be useful for some other research and doesn't come with much overhead to generate the EP probabilities. It's one of those things where on a gut feeling it certainly seems like EP would be more effective at cracking passwords, but as best as we can tell it over trains the resulting guess generator, and significantly penalizes making guesses with nonstandard endings.

**Comment by llCurious** [comment]
oh, I got it. nice @lakiw , thanks a lot for letting me know about this which confused me for a while XD. Now i figured it out how the algorithm works. 

By the way, the **enumPWD(level, length)** takes the **length** of the password into consideration to judge whether a candidate password is successfully generated. 

1. My understanding is to firstly select the length according to the **LN** in descending order. While during the generation phase, the CP and IP is _identical_ for different lengths. 
2. **Level** is in the range(0, 10) in the code, while in the paper is (-10, 0), for the prob takes log operation to do smoothing. My understanding is that in the code it multiples -1 (level = -1 * log(prob)). i wonder if it is necessary to do this.

I'd really appreciate it if you could point out whether there is any misunderstanding. Thanks again for you answers.

**Comment by lakiw** [comment]
I apologize that I'm going to take a step back and talk about the OMEN guess generation method vs. my actual code, simply because I'd have to look through my code again to remember the exact method I looped through the various LN, IP, and CP.

In OMEN, it will generate all the guesses for a particular OMEN level, before moving on to the next OMEN level. The total OMEN level for a guess is calculated by adding the level for the length of a guess, the IP, and all the following CPs. This means that various length guesses may be generated before moving over to the next OMEN level.

Another point is that the level of a length is dependent on the training. For example a length of 8 may have a level of 1, while a length of 6 may have a level of 5, if most of the passwords in the training set were length 8.

I *think* what I did to simplify things in the code was for a particular target OMEN level, I would start with the lengths of the lowest cost, and then recursively try to fill them out with initially the lowest possible level IP and following lowest possible CPs until I hit the last CP and saw if there existed ones that had the cost to make the sum add up to the target OMEN level. I'd then go back up a step and increase the level of that step step and go forward, until I could not increase the level any more, and then go back one more step and do it all again. As I said recursive ;p

**Comment by lakiw** [comment]
As to your second question, it's useful to separate the training from the guess generation. That smoothing is part of the training, but once we are generating guesses I think everyone preferred to think of the levels as positive numbers with it starting at 0 and incrementing as more guesses are generated. I will say though that the smoothing algorithm has a lot of potential for improvement.
